package stringeditor

// StringEntry defines the metadata for a single editable string.
// It maps a JSON key to a human-readable label and description,
// matching the original Pascal STRINGS.PAS "things" array.
type StringEntry struct {
	Label       string // Display name shown in the editor list
	Key         string // JSON key in strings.json
	Description string // Help text shown in the description bar
}

// StringEntries returns the ordered list of all editable strings.
// The first 178 entries match the original Pascal STRINGS.EXE ordering.
// V3-specific strings follow in logical groups.
func StringEntries() []StringEntry {
	return []StringEntry{
		// === Original Vision/2 Strings (matching Pascal things[] order) ===

		// Page 1: Items 1-20
		{Label: "Default User's Prompt", Key: "defPrompt", Description: "This is the Default prompt for new users"},
		{Label: "System Pause String", Key: "pauseString", Description: "This is displayed anytime the screen pauses awaiting a key to be pressed"},
		{Label: "System Password String", Key: "systemPasswordStr", Description: "This is displayed when asking the login password (if no SYSPASS.ANS)"},
		{Label: "Enter Alias String", Key: "whatsYourAlias", Description: "This is displayed when asking a user's alias (if ALIAS.ANS isn't in use)"},
		{Label: "Enter Password String", Key: "whatsYourPw", Description: "This is displayed when asking a user's password (if PASSWORD.ANS isn't used)"},
		{Label: "SysOp Working String", Key: "sysopWorkingStr", Description: "This is displayed when the SysOp hits [F2] while a user is online"},
		{Label: "Enter Chat String", Key: "enterChat", Description: "This is displayed when the sysop hits F2,F3,F4 to enter chat"},
		{Label: "Exit Chat String", Key: "exitChat", Description: "This is displayed when the sysop exits out of chat"},
		{Label: "SysOp In Dos String", Key: "sysopInDos", Description: "This is displayed to the user online when you Shell to DOS"},
		{Label: "Quote Starting Line", Key: "quoteStartLine", Description: "When asking Start Line to Quote |ST=Start Line |EN=Max Lines"},
		{Label: "Quote End Line", Key: "quoteEndLine", Description: "When asking End line to Quote |ST=Start Line |EN=Max Line"},
		{Label: "Connect String", Key: "connectionStr", Description: "This is the modem connect string displayed to user (|BR = Baud Rate)"},
		{Label: "Locked Baud String", Key: "lockedBaudStr", Description: "This string is displayed after the connect string if the baud is locked"},
		{Label: "Apply as New String", Key: "applyAsNewStr", Description: "Displayed when asking a new user if he wished to apply (@ = Yes/No Bar)"},
		{Label: "New User Pw Prompt", Key: "getNupStr", Description: "This is the prompt displayed before a new user enters the NUP (If Any..)"},
		{Label: "Request Chat Prompt", Key: "chatRequestStr", Description: "This prompt is displayed when a user requests chat (If CHAT.ANS not used)"},
		{Label: "Leave Feedback Prompt", Key: "leaveFBStr", Description: "This prompt is displayed when a user want to leave Feedback (@=Yes/No Bar)"},
		{Label: "Quoting Title", Key: "quoteTitle", Description: "Displayed when quoting a message  |TI=Title |FR=From"},
		{Label: "Quote which message", Key: "quoteMessageStr", Description: "Prompt for quoting which message |NU=Default Number"},
		{Label: "Erasing 5 Msgs Prompt", Key: "erase5MsgsStr", Description: "This is displayed when clearing 5 post out of a message base to create room"},

		// Page 2: Items 21-40
		{Label: "Change Sub-Board Prompt", Key: "changeBoardStr", Description: "This is used when a user hits 'A'/'*' to change areas in the Msg. Base"},
		{Label: "NewScanning Board String", Key: "newscanBoardStr", Description: "This is displayed for each Sub-Board that is newscanned (|CB = Current Board)"},
		{Label: "Not Used (extra3)", Key: "_extra3", Description: "Reserved - not currently used"},
		{Label: "Not Used (extra11)", Key: "_extra11", Description: "Reserved - not currently used"},
		{Label: "Post on Current Board", Key: "postOnBoardStr", Description: "Used when asking if a user wants to leave a Post ( |CB=Current Board )"},
		{Label: "Message Title String", Key: "msgTitleStr", Description: "This is displayed when a user is asked what he wishes to title a message"},
		{Label: "Send Message To String", Key: "msgToStr", Description: "This is displayed when a user is asked who he wishes to send the msg to"},
		{Label: "Upload a Message String", Key: "uploadFileStr", Description: "This is displayed when asking a user if he wishes to upload a message"},
		{Label: "Post Anonymous String", Key: "msgAnonStr", Description: "This is displayed when asking a user if he wished to post Anonymous"},
		{Label: "Save/Quote/Abort String", Key: "slashStr", Description: "This String is displayed in the message editor Save/Quote/Abort prompt"},
		{Label: "Not Used (extra7a)", Key: "_extra7a", Description: "Reserved - not currently used"},
		{Label: "NewScanning Current Area", Key: "newScanningStr", Description: "This is displayed for each file area that is newscanned (|AN = Area Name)"},
		{Label: "File Area Change", Key: "changeFileAreaStr", Description: "This is the prompt that is displayed when asking a user what area to change to"},
		{Label: "Log Off String", Key: "logOffStr", Description: "Displayed when user hit [G] to Logoff (If LOGOFF.ANS is not used)"},
		{Label: "Change Auto Message?", Key: "changeAutoMsgStr", Description: "Displayed when asking if user wishes to change auto-message"},
		{Label: "New User Handle", Key: "newUserNameStr", Description: "This is displayed when asking a New User's Handle"},
		{Label: "New User Password", Key: "createAPassword", Description: "This is diplayed when asking a New User to specify a password"},
		{Label: "SysOp is IN String", Key: "sysOpIsIn", Description: "Displayed at login if you are available for chat"},
		{Label: "SysOp is OUT String", Key: "sysOpIsOut", Description: "Displayed at login if you are not available for chat"},
		{Label: "One Line Header", Key: "headerStr", Description: "This is the One-Line Header displayed all over.. |HD = String"},

		// Page 3: Items 41-60
		{Label: "Not Used (extra7b)", Key: "_extra7b", Description: "Reserved - not currently used"},
		{Label: "Current File Area", Key: "curFileArea", Description: "Displays current file area user is in"},
		{Label: "Quoting Top Line", Key: "quoteTop", Description: "Quoted Section (Top); ^N=Author ^T=Title ^F=Who To ^D=Date ^W=Time"},
		{Label: "Quoting Bottom Line", Key: "quoteBottom", Description: "Quoted Section (Bottom); ^N=Author ^T=Title ^F=Who To ^D=Date ^W=Time"},
		{Label: "NewScan From What Date", Key: "newScanDateStr", Description: "Displayed when asking NewScan Date; |NS = User's Last NewScan"},
		{Label: "Add Batch Prompt", Key: "addBatchPrompt", Description: "Displayed when asking for a range to add to batch"},
		{Label: "View Archive Prompt", Key: "viewArchivePrompt", Description: "Displayed when asking for a range of files to view"},
		{Label: "Get File Info Prompt", Key: "getInfoPrompt", Description: "Displayed when asking for a range of files to get info on"},
		{Label: "Type a Text File Prompt", Key: "typeFilePrompt", Description: "Displayed when asking for a range of files to type"},
		{Label: "Upload File Prompt", Key: "uploadFileStr", Description: "|NU = Current File Number; Asked for each file user enters to upload"},
		{Label: "Download Files Now Prompt", Key: "downloadStr", Description: "Valid Commands are e[X]it, [Cr] Continue; [A]dd More Files"},
		{Label: "Listing Range Prompt", Key: "listRange", Description: "|ST List String |SR = Start Range |ER = End Range"},
		{Label: "Continue List String", Key: "continueStr", Description: "Displayed when page is full; [Y]es [N]o or Non-[S]top"},
		{Label: "Conference Prompt", Key: "confPrompt", Description: "Displayed when selecting conference, |DE = Default Selection"},
		{Label: "Area NewScan Prompt", Key: "areaMsgNewScan", Description: "|CB=Current Bul |NB=Total Buls, Commands: [P]ost [S]kip [Q]uit [N]onStop"},
		{Label: "List Users Prompt", Key: "listUsers", Description: "Displayed when asking (A)lphabetical / (N)umerical"},
		{Label: "Ask One-Liner", Key: "askOneLiner", Description: "Asks user if he wished to enter a one-liner after displayed"},
		{Label: "Enter Your One-Liner", Key: "enterOneLiner", Description: "Displayed when user enters a One-Liner"},
		{Label: "Re-Enter PW Prompt", Key: "reEnterPassword", Description: "When prompting to re-enter a user password"},
		{Label: "Enter Real Name Prompt", Key: "enterRealName", Description: "When prompting for a user's real name"},

		// Page 4: Items 61-80
		{Label: "Enter User Note", Key: "enterUserNote", Description: "When prompting for a User Note"},
		{Label: "Enter Phone Number", Key: "enterNumber", Description: "When prompting for User Phone Number"},
		{Label: "Enter Number Header", Key: "enterNumberHeader", Description: "Displayed above 'Enter Phone Number' Prompt"},
		{Label: "New User Welcome", Key: "welcomeNewUser", Description: "Displayed to New Users before User Number"},
		{Label: "Your User Number", Key: "yourUserNum", Description: "When giving user his User Number (|UN = User Number)"},
		{Label: "New User Current Prompt", Key: "yourCurrentPrompt", Description: "Displayed to new users before displaying their prompt"},
		{Label: "Create new Prompt?", Key: "designNewPrompt", Description: "Displayed when asking if new user wants to re-configure his prompt"},
		{Label: "Use Hot Keys?", Key: "wantHotKeys", Description: "Displayed when asking if user wishes to use hotkeys"},
		{Label: "Show Rumors?", Key: "wantRumors", Description: "Displayed when asking if user wished to see rumors"},
		{Label: "Unknown User, Apply?", Key: "userNotFound", Description: "Asks unknown users if they wish to apply.."},
		{Label: "Infoforms Prompt", Key: "infoformPrompt", Description: "Infoforms Prompt (V)iew, (Q)uit or (#)"},
		{Label: "NewUser Infoforms Prompt", Key: "newInfoFormPrompt", Description: "NewUser Infoforms Prompt, (Q)uit or (#)"},
		{Label: "View which Infoform", Key: "viewWhichForm", Description: "Displayed when a user (V)iews his infoform"},
		{Label: "Checking Local Ratio", Key: "checkingPhoneNum", Description: "Displayed when checking local ratio"},
		{Label: "Checking User Database", Key: "checkingUserBase", Description: "Displayed when finding a place for new users"},
		{Label: "Name is already used", Key: "nameAlreadyUsed", Description: "Displayed when a newuser enters a name already in use"},
		{Label: "Invalid Name", Key: "invalidUserName", Description: "Displayed if new user enters an invalid name"},
		{Label: "System Password Is...", Key: "sysPwIs", Description: "|PW = System Password; Displayed when checking for System PW"},
		{Label: "Access too Low", Key: "notValidated", Description: "Displayed when user's access is too low (when getting sys pw)"},
		{Label: "Mail Waiting Header", Key: "haveMail", Description: "Displayed to users w/mail waiting (|MA = # Mail)"},

		// Page 5: Items 81-100
		{Label: "Read Mail Now?", Key: "readMailNow", Description: "Asks if user wishes to read waiting mail (|MA = # Mail)"},
		{Label: "Delete Notice Files?", Key: "deleteNotice", Description: "Displayed when asking if user wishes to delete his notices"},
		{Label: "Feedback Waiting", Key: "haveFeedback", Description: "Displayed to sysop's with feedback waiting (|FB=#Feedback)"},
		{Label: "Read Feedback Now?", Key: "readFeedback", Description: "Displayed when asking if SysOp wishes to read feedback"},
		{Label: "Login Now?", Key: "loginNow", Description: "Displayed after user checks (and gets) the system password"},
		{Label: "New Users Waiting", Key: "newUsersWaiting", Description: "If using NUV this is displayed to notify users (|NE = #New)"},
		{Label: "Vote on New Users", Key: "voteOnNewUsers", Description: "When asking Users if they wish to vote on New Users"},
		{Label: "Adding BBS Name", Key: "addBBSName", Description: "Displayed when adding to the BBS List (Name)"},
		{Label: "Adding BBS Number", Key: "addBBSNumber", Description: "Displayed when adding to the BBS List (Number)"},
		{Label: "Adding BBS Baud", Key: "addBBSBaud", Description: "Dispayed when adding to the BBS List (Baud)"},
		{Label: "Adding BBS Software", Key: "addBBSSoftware", Description: "Displayed when adding to the BBS List (Software)"},
		{Label: "Add Extended BBS Descrip", Key: "addExtendedBBSDescr", Description: "Displayed when asking if user wants to add extended descrip."},
		{Label: "BBS Entry Added", Key: "bbsEntryAdded", Description: "Displayed after adding to the BBS List"},
		{Label: "View Next Extended Desc", Key: "viewNextDescrip", Description: "Displayed when viewing extended BBS descrips. (If > 1)"},
		{Label: "Joined Message Conf.", Key: "joinedMsgConf", Description: "Displayed when joining Message Conf (|NA=Name, |NU=#)"},
		{Label: "Joined File Conf.", Key: "joinedFileConf", Description: "Displayed when joining File Conf (|NA=Name, |NU=#)"},
		{Label: "Who's being voted on", Key: "whosBeingVotedOn", Description: "(|NA = Name) displays NUV victim's name"},
		{Label: "Number of YES Votes", Key: "numYesVotes", Description: "(|YV = Yes Votes) displays # of YES Votes"},
		{Label: "Number of NO Votes", Key: "numNoVotes", Description: "(|NV = No Votes) displays # of NO Votes"},
		{Label: "NUV Comment Header", Key: "nuvCommentHeader", Description: "Displayed above Comments on New User"},

		// Page 6: Items 101-120
		{Label: "Enter NUV Comment", Key: "enterNUVCommentPrompt", Description: "Prompt displayed when asking for a comment on new user"},
		{Label: "NUV Vote Prompt", Key: "nuvVotePrompt", Description: "(If BARS are off) Prompt displayed when voting on user"},
		{Label: "Yes Vote Cast", Key: "yesVoteCast", Description: "Displayed when YES is cast (|NA=Name)"},
		{Label: "No Vote Cast", Key: "noVoteCast", Description: "Displayed when NO is cast (|NA=Name)"},
		{Label: "No New Users Pending", Key: "noNewUsersPending", Description: "Displayed when no New User Voting victims exist"},
		{Label: "Enter Rumor Title", Key: "enterRumorTitle", Description: "Prompt displayed when entering a rumor title"},
		{Label: "Add Rumor Anonymous?", Key: "addRumorAnonymous", Description: "Add Rumor Anonymous prompt"},
		{Label: "Enter Rumor Level", Key: "enterRumorLevel", Description: "Lowest Level allowed to see rumor prompt"},
		{Label: "Enter Rumor Prompt", Key: "enterRumorPrompt", Description: "Prompt for entering a new rumor"},
		{Label: "Rumor Added!", Key: "rumorAdded", Description: "Displayed after a rumor has been added"},
		{Label: "List Rumors Prompt", Key: "listRumorsPrompt", Description: "Valid Commands: (R)umors, (S)tats, (B)oth, (E)xit"},
		{Label: "Send Mail To Who", Key: "sendMailToWho", Description: "Displayed when asking who to send mail to."},
		{Label: "Carbon Copy Mail", Key: "carbonCopyMail", Description: "Carbon Copy Mail to Who Prompt"},
		{Label: "Notify E-Mail", Key: "notifyEMail", Description: "Asks if user would like to be notified when read"},
		{Label: "E-Mail Announcement", Key: "eMailAnnouncement", Description: "Prompt, Commands: (C)hange/Create, (D)elete, (Q)uit"},
		{Label: "SysOp not here", Key: "sysOpNotHere", Description: "Displayed if user request chat while you are not around"},
		{Label: "Chat Costs Header", Key: "chatCostsHeader", Description: "(|CC = Chat Cost) header displayed if chat costs FP's"},
		{Label: "Still want to try?", Key: "stillWantToTry", Description: "Displayed when asking user still wants to pay for chat"},
		{Label: "Not enough file points", Key: "notEnoughFPPoints", Description: "Displayed if user doesn't have enough file points!"},
		{Label: "[C] Turns off chat", Key: "chatCallOff", Description: "Displayed after user invokes chat call"},

		// Page 7: Items 121-140
		{Label: "[C] Turns chat call on", Key: "chatCallOn", Description: "Displayed after user turns chat call off"},
		{Label: "Feedback Sent!", Key: "feedbackSent", Description: "Displayed after user sends feedback."},
		{Label: "You have read mail", Key: "youHaveReadMail", Description: "Header when deleting mail (|TI=Title/|SB=Sent By)"},
		{Label: "Delete mail now", Key: "deleteMailNow", Description: "When asking if user wants to delete mail"},
		{Label: "Current Mail (None)", Key: "currentMailNone", Description: "When displaying mail and there is none"},
		{Label: "Current Mail Reading", Key: "currentMailWaiting", Description: "|NU = Number, |TI = Title, |AU = Author"},
		{Label: "Pick this mail header?", Key: "pickMailHeader", Description: "When asking if user wants to use this mail header"},
		{Label: "List Title Type", Key: "listTitleType", Description: "Either by (R)ange or (N)ext in Line"},
		{Label: "No More Titles to List", Key: "noMoreTitles", Description: "Displayed when no more titles to list."},
		{Label: "List Titles to you?", Key: "listTitlesToYou", Description: "When asking if user only wishes to list titles to himself"},
		{Label: "Sub doesn't exist!", Key: "subDoesNotExist", Description: "Displayed when user trys to enter a Sub that doesn't exist"},
		{Label: "Msg. NewScan Aborted", Key: "msgNewScanAborted", Description: "Displayed if user aborts Message NewScan"},
		{Label: "Message NewScan Prompt", Key: "msgNewScanPrompt", Description: "(If No Bars) |BN=Board Name |CB=Cur. Msg # |NB=Total Msgs."},
		{Label: "Reading Msg. Prompt", Key: "msgReadingPrompt", Description: "(If No Bars) |BN=Board Name |CB=Cur. Msg # |NB=Total Msgs."},
		{Label: "Current Sub (NewScan)", Key: "currentSubNewScan", Description: "Current Sub Display |BN=Board Name |NU=Board #"},
		{Label: "Jump to Message #", Key: "jumpToMessageNum", Description: "Displayed when jumping messages (|NB=Total Msgs)"},
		{Label: "Posting QWK Msg.", Key: "postingQWKMsg", Description: "When adding a QWK Packet |TO=Total |BN=Board Name"},
		{Label: "Total QWK Added", Key: "totalQWKAdded", Description: "Total Messages Added (|TO=Total)"},
		{Label: "Sending QWK Packet", Key: "sendQWKPacketPrompt", Description: "Displayed before sending QWK Packet - [Q]uits"},
		{Label: "Not Used (extra8)", Key: "_extra8", Description: "Reserved - not currently used"},

		// Page 8: Items 141-160
		{Label: "Not Used (extra9)", Key: "_extra9", Description: "Reserved - not currently used"},
		{Label: "Not Used (extra10)", Key: "_extra10", Description: "Reserved - not currently used"},
		{Label: "Thread Which-Way?", Key: "threadWhichWay", Description: "Prompts when user wants to message thread (F)ore, (B)ack"},
		{Label: "Auto-Validating File", Key: "autoValidatingFile", Description: "Displayed when auto-validating a new upload |FN=Filename"},
		{Label: "File is Worth..", Key: "fileIsWorth", Description: "|FP=File Points |FS=FileSize - after Auto-Validating File"},
		{Label: "Granting User FP's", Key: "grantingUserFP", Description: "|FP = File Points - Displayed when giving user FP's for upload"},
		{Label: "File is Offline", Key: "fileIsOffline", Description: "Displayed if user tries to access offline file"},
		{Label: "Crashed File", Key: "crashedFile", Description: "Displayed if user tries to access an incomplete file"},
		{Label: "Bad Baud Rate", Key: "badBaudRate", Description: "Displayed if user tries to access files with a bad baud"},
		{Label: "UnValidated File", Key: "unvalidatedFile", Description: "Displayed if user tries to access an unvalidated file"},
		{Label: "Special File", Key: "specialFile", Description: "Displayed if user tries to access a 'special' file"},
		{Label: "No Downloads Here", Key: "noDownloadsHere", Description: "Displayed if user tries to download from a non-download area"},
		{Label: "Private File", Key: "privateFile", Description: "Displayed if user tries to download a private file"},
		{Label: "File Password", Key: "filePassword", Description: "When Prompting for password on passworded files"},
		{Label: "Wrong File PW", Key: "wrongFilePW", Description: "Displayed if user enters wrong file password"},
		{Label: "File List Prompt", Key: "fileListPrompt", Description: "Displayed when listing files (after a full page) |AN=Area Name"},
		{Label: "Invalid File Selection", Key: "invalidArea", Description: "Displayed if user enters an invalid #/Name"},
		{Label: "Untagging Batch File", Key: "untaggingBatchFile", Description: "Displayed when removing file from Batch list (|FN=Filename)"},
		{Label: "File NewScan Prompt", Key: "fileNewScanPrompt", Description: "Prompt displayed when newscanning files - |AN = Area Name"},
		{Label: "File Extraction Prompt", Key: "fileExtractionPrompt", Description: "[A]dd to Batch or [Q]uit - displayed after extracting a zip"},

		// Page 9: Items 161-178
		{Label: "Bad UD Ratio", Key: "badUDRatio", Description: "|RA=Upload/Download Ratio |RR=Required Ratio"},
		{Label: "Bad UD 'K' Ratio", Key: "badUDKRatio", Description: "|RA=Upload/Download Kilobyte Ratio |RR=Required Ratio"},
		{Label: "Exceeded Daily KB Limit", Key: "exceededDailyKBLimit", Description: "|DK = Downloaded K Today  |KL = Kilobyte Limit"},
		{Label: "File Point Commission", Key: "filePointCommision", Description: "|NA = Who's getting points |FP = how many file points"},
		{Label: "Successful Download", Key: "successfulDownload", Description: "|FN=Filename |CP=CPS |CO=File Cost |ER=# Errors"},
		{Label: "File Crash, Save?", Key: "fileCrashSave", Description: "Displayed if transfer crashed, save partial file?"},
		{Label: "Invalid Upload Name", Key: "invalidFilename", Description: "Displayed if user enters an invalid filename to upload"},
		{Label: "Already Entered Filename", Key: "alreadyEnteredFilename", Description: "Displayed if user enters a filename already in upload queue"},
		{Label: "File Already Exists!", Key: "fileAlreadyExists", Description: "Displayed if user enters a filename that already exists"},
		{Label: "Enter File Description", Key: "enterFileDescription", Description: "Enter File Description Prompt"},
		{Label: "Extended Upload Setup", Key: "extendedUploadSetup", Description: "Valid Commands = [A]dd Password, [P]rivate, [D]esc., [Cr] Quit"},
		{Label: "Re-Enter File Descrip.", Key: "reEnterFileDescrip", Description: "Prompted after batch uploads if no description exists"},
		{Label: "Notify if Downloaded", Key: "notifyIfDownloaded", Description: "Prompted after downloads"},
		{Label: "50 Files Maximum", Key: "fiftyFilesMaximum", Description: "Displayed if user tries to add more than 50 files to batch"},
		{Label: "You can't download here", Key: "youCantDownloadHere", Description: "Displayed to a user who is not allowed to download from area"},
		{Label: "File is already marked", Key: "fileAlreadyMarked", Description: "Displayed to a user who tags a marked file"},
		{Label: "Not enough File Points", Key: "notEnoughFP", Description: "Displayed when user tries to leech without enough file points"},
		{Label: "File Area Password", Key: "fileAreaPassword", Description: "When prompting for file area password."},

		// === V3-Specific Strings ===

		// General / Misc
		{Label: "Anonymous Name", Key: "anonymousName", Description: "The name shown for anonymous posts"},
		{Label: "Wrong Password", Key: "wrongPassword", Description: "Displayed when user enters wrong password"},
		{Label: "Yes Prompt Text", Key: "yesPromptText", Description: "Text for 'Yes' in yes/no prompts"},
		{Label: "No Prompt Text", Key: "noPromptText", Description: "Text for 'No' in yes/no prompts"},
		{Label: "Abort Message Prompt", Key: "abortMessagePrompt", Description: "Confirmation prompt when aborting a message"},
		{Label: "Quote Prefix", Key: "QuotePrefix", Description: "Prefix added to quoted lines in messages"},
		{Label: "One-Liner Legend", Key: "One_Liner_Legend", Description: "Color code legend shown when entering one-liners"},
		{Label: "One-Liner Anon Prompt", Key: "oneLinerAnonymousPrompt", Description: "Asks if user wants to post one-liner anonymously"},

		// Chat (V3)
		{Label: "Chat Header", Key: "chatHeader", Description: "Header displayed when entering teleconference chat"},
		{Label: "Chat Separator", Key: "chatSeparator", Description: "Line separator in chat display"},
		{Label: "Chat User Entered", Key: "chatUserEntered", Description: "Message shown when a user enters chat (%s=username)"},
		{Label: "Chat User Left", Key: "chatUserLeft", Description: "Message shown when a user leaves chat (%s=username)"},
		{Label: "Chat System Prefix", Key: "chatSystemPrefix", Description: "Prefix for system messages in chat (%s=message)"},
		{Label: "Chat Message Format", Key: "chatMessageFormat", Description: "Format for chat messages (%s=user, %s=message)"},

		// Page/Node (V3)
		{Label: "Page: Online Nodes Hdr", Key: "pageOnlineNodesHeader", Description: "Header for online nodes list when paging"},
		{Label: "Page: Node List Entry", Key: "pageNodeListEntry", Description: "Format for each node in the list (%d=node, %s=user)"},
		{Label: "Page: Which Node", Key: "pageWhichNodePrompt", Description: "Prompt asking which node to page"},
		{Label: "Page: Message Prompt", Key: "pageMessagePrompt", Description: "Prompt for page message text"},
		{Label: "Page: Message Format", Key: "pageMessageFormat", Description: "Format of received page (%s=from, %s=msg)"},
		{Label: "Page: Sent", Key: "pageSent", Description: "Confirmation that page was sent (%d=node)"},
		{Label: "Page: Cancelled", Key: "pageCancelled", Description: "Shown when page is cancelled"},
		{Label: "Page: Invalid Node", Key: "pageInvalidNode", Description: "Shown for invalid node number"},
		{Label: "Page: Self Error", Key: "pageSelfError", Description: "Shown when trying to page yourself"},
		{Label: "Page: Node Offline", Key: "pageNodeOffline", Description: "Shown when target node is not online"},

		// New User (V3)
		{Label: "New Users Closed", Key: "newUsersClosedStr", Description: "Shown when new user registration is disabled"},
		{Label: "New User: Location", Key: "newUserLocationPrompt", Description: "Prompt for new user's location/group"},
		{Label: "New User: PW Too Short", Key: "newUserPasswordTooShort", Description: "Shown when new user password is too short"},
		{Label: "New User: PW Mismatch", Key: "newUserPasswordMismatch", Description: "Shown when password confirmation doesn't match"},
		{Label: "New User: Invalid Name", Key: "newUserInvalidRealName", Description: "Shown when real name format is invalid"},
		{Label: "New User: Too Many Try", Key: "newUserTooManyAttempts", Description: "Shown after too many invalid attempts"},
		{Label: "New User: Created", Key: "newUserAccountCreated", Description: "Shown after account creation (pending validation)"},
		{Label: "New User: Error", Key: "newUserCreationError", Description: "Shown on account creation error"},
		{Label: "New User: Maybe Later", Key: "newUserMaybeAnotherTime", Description: "Shown when new user declines to apply"},

		// Stats (V3)
		{Label: "Stats: BBS Name", Key: "statsBBSName", Description: "Format for BBS name in stats display (%s=name)"},
		{Label: "Stats: SysOp", Key: "statsSysOp", Description: "Format for SysOp name in stats display (%s=name)"},
		{Label: "Stats: Version", Key: "statsVersion", Description: "Format for version in stats display (%s=version)"},
		{Label: "Stats: Total Users", Key: "statsTotalUsers", Description: "Format for total users in stats (%s=count)"},
		{Label: "Stats: Total Calls", Key: "statsTotalCalls", Description: "Format for total calls in stats (%s=count)"},
		{Label: "Stats: Total Messages", Key: "statsTotalMessages", Description: "Format for total messages in stats (%s=count)"},
		{Label: "Stats: Total Files", Key: "statsTotalFiles", Description: "Format for total files in stats (%s=count)"},
		{Label: "Stats: Active Nodes", Key: "statsActiveNodes", Description: "Format for active nodes in stats (%s/%s)"},
		{Label: "Stats: Date", Key: "statsDate", Description: "Format for date in stats display (%s=date)"},
		{Label: "Stats: Time", Key: "statsTime", Description: "Format for time in stats display (%s=time)"},

		// User Config (V3)
		{Label: "Cfg: Toggle ON", Key: "cfgToggleOn", Description: "Text shown when a toggle is ON"},
		{Label: "Cfg: Toggle OFF", Key: "cfgToggleOff", Description: "Text shown when a toggle is OFF"},
		{Label: "Cfg: Toggle Format", Key: "cfgToggleFormat", Description: "Format for toggle display (%s=label, %s=state)"},
		{Label: "Cfg: Save Error", Key: "cfgSaveError", Description: "Shown on config save error (%s=setting)"},
		{Label: "Cfg: Screen Width", Key: "cfgScreenWidthPrompt", Description: "Prompt for screen width setting"},
		{Label: "Cfg: Width Invalid", Key: "cfgScreenWidthInvalid", Description: "Shown for invalid screen width"},
		{Label: "Cfg: Width Set", Key: "cfgScreenWidthSet", Description: "Confirmation of screen width change (%d=width)"},
		{Label: "Cfg: Screen Height", Key: "cfgScreenHeightPrompt", Description: "Prompt for screen height setting"},
		{Label: "Cfg: Height Invalid", Key: "cfgScreenHeightInvalid", Description: "Shown for invalid screen height"},
		{Label: "Cfg: Height Set", Key: "cfgScreenHeightSet", Description: "Confirmation of screen height change (%d=height)"},
		{Label: "Cfg: Term Type Set", Key: "cfgTermTypeSet", Description: "Shown after changing terminal type (%s=type)"},
		{Label: "Cfg: String Prompt", Key: "cfgStringPrompt", Description: "Prompt for string setting (%s=label, %d=max)"},
		{Label: "Cfg: String w/Current", Key: "cfgStringPromptCurrent", Description: "Prompt showing current value (%s=label, %s=current, %d=max)"},
		{Label: "Cfg: String Updated", Key: "cfgStringUpdated", Description: "Confirmation of string update (%s=label)"},
		{Label: "Cfg: Current PW Prompt", Key: "cfgCurrentPwPrompt", Description: "Prompt for current password verification"},
		{Label: "Cfg: Incorrect PW", Key: "cfgIncorrectPw", Description: "Shown when current password is wrong"},
		{Label: "Cfg: PW Changed", Key: "cfgPasswordChanged", Description: "Confirmation of password change"},
		{Label: "Cfg: Color Select", Key: "cfgColorSelectPrompt", Description: "Prompt for selecting a color (%s=name)"},
		{Label: "Cfg: Color Input", Key: "cfgColorInputPrompt", Description: "Prompt for color number input"},
		{Label: "Cfg: Color Invalid", Key: "cfgColorInvalid", Description: "Shown for invalid color number"},
		{Label: "Cfg: Color Set", Key: "cfgColorSet", Description: "Confirmation of color change"},
		{Label: "Cfg: Prompt Help", Key: "cfgCustomPromptHelp", Description: "Help text for custom prompt codes"},
		{Label: "Cfg: View Width", Key: "cfgViewScreenWidth", Description: "Display format for screen width in settings"},
		{Label: "Cfg: View Height", Key: "cfgViewScreenHeight", Description: "Display format for screen height in settings"},
		{Label: "Cfg: View Term", Key: "cfgViewTermType", Description: "Display format for terminal type in settings"},
		{Label: "Cfg: View HotKeys", Key: "cfgViewHotKeys", Description: "Display format for hotkeys setting"},
		{Label: "Cfg: View More", Key: "cfgViewMorePrompts", Description: "Display format for more prompts setting"},
		{Label: "Cfg: View Msg Header", Key: "cfgViewMsgHeader", Description: "Display format for message header setting"},
		{Label: "Cfg: View Prompt", Key: "cfgViewCustomPrompt", Description: "Display format for custom prompt"},
		{Label: "Cfg: View PromptColor", Key: "cfgViewPromptColor", Description: "Display format for prompt/input colors"},
		{Label: "Cfg: View TextColor", Key: "cfgViewTextColor", Description: "Display format for text/stat colors"},
		{Label: "Cfg: View Text2Color", Key: "cfgViewText2Color", Description: "Display format for text2/stat2 colors"},
		{Label: "Cfg: View BarColor", Key: "cfgViewBarColor", Description: "Display format for bar color"},
		{Label: "Cfg: View RealName", Key: "cfgViewRealName", Description: "Display format for real name"},
		{Label: "Cfg: View Phone", Key: "cfgViewPhone", Description: "Display format for phone number"},
		{Label: "Cfg: View Note", Key: "cfgViewNote", Description: "Display format for user note"},

		// Message Reader (V3)
		{Label: "Msg: End of Messages", Key: "msgEndOfMessages", Description: "Shown at end of message list"},
		{Label: "Msg: First Message", Key: "msgFirstMessage", Description: "Shown when already at first message"},
		{Label: "Msg: Reply Deferred", Key: "msgMailReplyDeferred", Description: "Shown when mail reply is not yet implemented"},
		{Label: "Msg: List Deferred", Key: "msgListDeferred", Description: "Shown when message list is not yet implemented"},
		{Label: "Msg: Hdr Load Error", Key: "msgHdrLoadError", Description: "Shown when message header template fails to load"},
		{Label: "Msg: Board Info Fmt", Key: "msgBoardInfoFormat", Description: "Format for message board info bar"},
		{Label: "Msg: Scroll Percent", Key: "msgScrollPercent", Description: "Format for scroll percentage indicator"},
		{Label: "Msg: NewScan Suffix", Key: "msgNewScanSuffix", Description: "Suffix added during newscan mode"},
		{Label: "Msg: Reading Suffix", Key: "msgReadingSuffix", Description: "Suffix added during reading mode"},
		{Label: "Msg: Thread Prompt", Key: "msgThreadPrompt", Description: "Prompt for thread navigation direction"},
		{Label: "Msg: No Thread Found", Key: "msgNoThreadFound", Description: "Shown when no thread is found (%s=direction)"},
		{Label: "Msg: Jump Prompt", Key: "msgJumpPrompt", Description: "Prompt for jumping to a message number"},
		{Label: "Msg: Invalid Num", Key: "msgInvalidMsgNum", Description: "Shown for invalid message number"},
		{Label: "Msg: Reply Empty Subj", Key: "msgReplySubjectEmpty", Description: "Shown when reply subject is empty"},
		{Label: "Msg: Launching Editor", Key: "msgLaunchingEditor", Description: "Shown when launching message editor"},
		{Label: "Msg: Reply Cancelled", Key: "msgReplyCancelled", Description: "Shown when reply is cancelled"},
		{Label: "Msg: Reply Error", Key: "msgReplyError", Description: "Shown on reply save error"},
		{Label: "Msg: Reply Success", Key: "msgReplySuccess", Description: "Shown on successful reply post"},
		{Label: "Msg: Editor Error", Key: "msgEditorError", Description: "Shown on editor error"},

		// Message Scan (V3)
		{Label: "Scan: Date Line", Key: "scanDateLine", Description: "Display format for scan date filter"},
		{Label: "Scan: To Line", Key: "scanToLine", Description: "Display format for scan 'to' filter"},
		{Label: "Scan: From Line", Key: "scanFromLine", Description: "Display format for scan 'from' filter"},
		{Label: "Scan: Range Line", Key: "scanRangeLine", Description: "Display format for scan range filter"},
		{Label: "Scan: Update Line", Key: "scanUpdateLine", Description: "Display format for scan update pointers setting"},
		{Label: "Scan: Which Line", Key: "scanWhichLine", Description: "Display format for scan area selection"},
		{Label: "Scan: Abort Line", Key: "scanAbortLine", Description: "Display format for scan abort option"},
		{Label: "Scan: Selection", Key: "scanSelectionPrompt", Description: "Prompt for scan selection (Cr/Scan)"},
		{Label: "Scan: Date Prompt", Key: "scanDatePrompt", Description: "Prompt for scan date filter value"},
		{Label: "Scan: To Prompt", Key: "scanToPrompt", Description: "Prompt for scan 'to' filter value"},
		{Label: "Scan: From Prompt", Key: "scanFromPrompt", Description: "Prompt for scan 'from' filter value"},
		{Label: "Scan: Range Start", Key: "scanRangeStartPrompt", Description: "Prompt for scan range start"},
		{Label: "Scan: Range End", Key: "scanRangeEndPrompt", Description: "Prompt for scan range end"},
		{Label: "Scan: Which Prompt", Key: "scanWhichPrompt", Description: "Prompt for scan area selection"},
		{Label: "Scan: Header", Key: "scanHeader", Description: "Header shown during message scanning"},
		{Label: "Scan: No Area", Key: "scanNoAreaSelected", Description: "Shown when no message area is selected"},
		{Label: "Scan: No Messages", Key: "scanNoMessages", Description: "Shown when area has no messages"},
		{Label: "Scan: No Tagged", Key: "scanNoTaggedAreas", Description: "Shown when no areas are tagged for newscan"},
		{Label: "Scan: Area Progress", Key: "scanAreaProgress", Description: "Progress display during area scan"},
		{Label: "Scan: Complete", Key: "scanComplete", Description: "Shown when newscan is complete"},
		{Label: "Scan: Login Required", Key: "scanLoginRequired", Description: "Shown when not logged in for scan"},
		{Label: "Scan: No Areas Avail", Key: "scanNoAreasAvailable", Description: "Shown when no areas are available"},
		{Label: "Scan: No Access Areas", Key: "scanNoAccessibleAreas", Description: "Shown when no accessible areas found"},
		{Label: "Scan: Config Saved", Key: "scanConfigSaved", Description: "Shown when newscan config is saved"},
		{Label: "Scan: Config Error", Key: "scanConfigError", Description: "Shown on newscan config save error"},
		{Label: "Scan: Cfg Login Req", Key: "scanConfigLoginRequired", Description: "Shown when not logged in for scan config"},

		// Message List (V3)
		{Label: "MsgList: Login Req", Key: "msgListLoginRequired", Description: "Shown when not logged in for message list"},
		{Label: "MsgList: No Area", Key: "msgListNoAreaSelected", Description: "Shown when no area selected for list"},
		{Label: "MsgList: Area Error", Key: "msgListAreaNotFound", Description: "Shown when message area not found"},
		{Label: "MsgList: Load Error", Key: "msgListLoadError", Description: "Shown on message list load error"},
		{Label: "MsgList: No Messages", Key: "msgListNoMessages", Description: "Shown when no messages in area"},

		// File Viewer (V3)
		{Label: "File: No Area", Key: "fileNoAreaSelected", Description: "Shown when no file area is selected"},
		{Label: "File: Prompt Format", Key: "filePromptFormat", Description: "Prompt format for file operations (%s=action)"},
		{Label: "File: Not Found", Key: "fileNotFoundFormat", Description: "Shown when file is not found (%s=name)"},
		{Label: "File: Locate Error", Key: "fileLocateError", Description: "Shown on file locate error"},
		{Label: "File: Viewing Header", Key: "fileViewingHeader", Description: "Header when viewing a file (%s=name)"},
		{Label: "File: End of File", Key: "fileEndOfFile", Description: "Shown at end of viewed file"},
		{Label: "File: More Prompt", Key: "fileMorePrompt", Description: "More prompt during file viewing"},
		{Label: "File: Pause Prompt", Key: "filePausePrompt", Description: "Pause prompt during file viewing"},
		{Label: "File: Open Error", Key: "fileOpenError", Description: "Shown on file open error"},

		// Door Handler (V3)
		{Label: "Door: Dropfile Error", Key: "doorDropfileError", Description: "Shown on door dropfile creation error (%s=door)"},
		{Label: "Door: Error Format", Key: "doorErrorFormat", Description: "General door error format (%s=error)"},
		{Label: "Door: Login Required", Key: "doorLoginRequired", Description: "Shown when not logged in for doors"},
		{Label: "Door: Prompt", Key: "doorPrompt", Description: "Door selection prompt (?=List, Q=Quit)"},
		{Label: "Door: Not Found", Key: "doorNotFoundFormat", Description: "Shown when door is not found (%s=name)"},
		{Label: "Door: None Configured", Key: "doorNoneConfigured", Description: "Shown when no doors are configured"},
		{Label: "Door: Template Error", Key: "doorTemplateError", Description: "Shown on door list template error"},
		{Label: "Door: Info Login Req", Key: "doorInfoLoginRequired", Description: "Shown when not logged in for door info"},

		// Matrix/Login (V3)
		{Label: "Matrix: Disconnecting", Key: "matrixDisconnecting", Description: "Shown when disconnecting from matrix"},
		{Label: "Matrix: Check Access", Key: "matrixCheckAccessPrompt", Description: "Prompt to check access level"},
		{Label: "Matrix: User Not Found", Key: "matrixUserNotFound", Description: "Shown when user not found in matrix"},
		{Label: "Matrix: Validated", Key: "matrixAccountValidated", Description: "Shown for validated account (%s=user, %d=level)"},
		{Label: "Matrix: Not Validated", Key: "matrixAccountNotValidated", Description: "Shown for unvalidated account"},
		{Label: "Idle Timeout", Key: "idleTimeout", Description: "Shown when user is disconnected for idle timeout"},

		// Conference (V3)
		{Label: "Conf: Login Required", Key: "confLoginRequired", Description: "Shown when not logged in for conferences"},
		{Label: "Conf: No Conferences", Key: "confNoConferences", Description: "Shown when no conferences configured"},
		{Label: "Conf: Not Found", Key: "confNotFound", Description: "Shown when conference not found (%s=name)"},
		{Label: "Conf: No Areas", Key: "confNoAccessibleAreas", Description: "Shown when no accessible areas in conference"},
		{Label: "Conf: Current Area", Key: "confCurrentAreaFormat", Description: "Display format for current area (%s=name, %s=conf)"},
		{Label: "Conf: Template Error", Key: "confTemplateError", Description: "Shown on conference template error"},
		{Label: "Conf: Nav Login Req", Key: "confNavLoginRequired", Description: "Shown when not logged in for conference nav"},
		{Label: "Conf: No Access Conf", Key: "confNoAccessibleConferences", Description: "Shown when no accessible conferences"},
		{Label: "Conf: No Access Areas", Key: "confNoAccessibleMsgAreas", Description: "Shown when no accessible msg areas"},
		{Label: "Conf: Area Tmpl Err", Key: "confAreaTemplateError", Description: "Shown on message area template error"},

		// Executor (V3)
		{Label: "Exec: Unknown Command", Key: "execUnknownCommand", Description: "Shown for unrecognized menu commands"},
		{Label: "Exec: Readmail Login", Key: "execReadmailLogin", Description: "Shown when not logged in for readmail"},
		{Label: "Exec: Readmail Holder", Key: "execReadmailPlaceholder", Description: "Placeholder for readmail (%s=user)"},
		{Label: "Exec: Door Login", Key: "execDoorLogin", Description: "Shown when not logged in for doors"},
		{Label: "Exec: Door Not Config", Key: "execDoorNotConfigured", Description: "Shown when door not configured (%s=name)"},
		{Label: "Exec: Goodbye", Key: "execGoodbye", Description: "Goodbye message on logoff"},
		{Label: "Exec: Stats Login", Key: "execStatsLogin", Description: "Shown when not logged in for stats"},
		{Label: "Exec: Stats Error", Key: "execStatsError", Description: "Shown on stats display error (%s=err)"},
		{Label: "Exec: OL Template Err", Key: "execOnelinerTemplateErr", Description: "Shown on oneliner template error"},
		{Label: "Exec: OL Color Error", Key: "execOnelinerColorError", Description: "Shown for invalid oneliner colors"},
		{Label: "Exec: OL Write Error", Key: "execOnelinerWriteError", Description: "Shown on oneliner write error"},
		{Label: "Exec: OL Added", Key: "execOnelinerAdded", Description: "Shown when oneliner is added"},
		{Label: "Exec: OL Empty", Key: "execOnelinerEmpty", Description: "Shown when oneliner is empty"},
		{Label: "Exec: Already Logged", Key: "execAlreadyLoggedIn", Description: "Shown when user is already logged in"},
		{Label: "Exec: Username Prompt", Key: "execUsernamePrompt", Description: "Prompt for username during login"},
		{Label: "Exec: Password Prompt", Key: "execPasswordPrompt", Description: "Prompt for password during login"},
		{Label: "Exec: Abort Login", Key: "execAbortLoginPrompt", Description: "Prompt to abort login"},
		{Label: "Exec: Login Cancelled", Key: "execLoginCancelled", Description: "Shown when login is cancelled"},
		{Label: "Exec: IP Lockout", Key: "execIPLockout", Description: "Shown when IP is locked out (%d=minutes)"},
		{Label: "Exec: Login Incorrect", Key: "execLoginIncorrect", Description: "Shown for incorrect login"},
		{Label: "Exec: Not Validated", Key: "execNotValidated", Description: "Shown for unvalidated accounts"},
		{Label: "Exec: Menu Load Err", Key: "execMenuLoadError", Description: "Shown on menu load error (%s=menu, %v=err)"},
		{Label: "Exec: Menu PW Prompt", Key: "execMenuPasswordPrompt", Description: "Prompt for menu password (%s=menu, %d=attempt)"},
		{Label: "Exec: PW Accepted", Key: "execPasswordAccepted", Description: "Shown when password is correct"},
		{Label: "Exec: Incorrect PW", Key: "execIncorrectPassword", Description: "Shown when password is wrong"},
		{Label: "Exec: Too Many Tries", Key: "execTooManyAttempts", Description: "Shown after too many password attempts"},
		{Label: "Exec: Access Denied", Key: "execAccessDenied", Description: "Shown when access is denied"},
		{Label: "Exec: LastCall TmplErr", Key: "execLastcallTemplateErr", Description: "Shown on last callers template error"},
		{Label: "Exec: File Load Error", Key: "execFileLoadError", Description: "Shown on file load error (%s=file)"},
		{Label: "Exec: No New Mail", Key: "execNoNewMail", Description: "Shown when no new mail"},
		{Label: "Exec: New Mail Count", Key: "execNewMailCount", Description: "Shown with new mail count (%d=count)"},
		{Label: "Exec: UList Tmpl Err", Key: "execUserlistTemplateErr", Description: "Shown on user list template error"},
		{Label: "Exec: Pending Valid", Key: "execPendingValidation", Description: "Shown with pending validation count (%d=count)"},
		{Label: "Exec: Run Cmd Error", Key: "execRunCommandError", Description: "Shown on command run error (%s=cmd, %v=err)"},
		{Label: "Exec: Cmd Not Found", Key: "execRunCommandNotFound", Description: "Shown when command not found (%s=cmd)"},
		{Label: "Exec: Run Door Error", Key: "execRunDoorError", Description: "Shown on door run error (%s=door, %v=err)"},
		{Label: "Exec: Login Critical", Key: "execLoginCriticalError", Description: "Shown on critical login config error (Missing P/O)"},
		{Label: "Exec: Version String", Key: "execVersionString", Description: "Version string format (%s=version)"},

		// Terminal / Session (V3)
		{Label: "Term: Size Detected", Key: "termSizeNewDetectedPrompt", Description: "Prompt when new terminal size is detected"},
		{Label: "Term: Update Defaults", Key: "termSizeUpdateDefaultsPrompt", Description: "Prompt to update default terminal size"},
		{Label: "Invisible Logon", Key: "invisibleLogonPrompt", Description: "Prompt for invisible (hidden) logon"},
	}
}
